apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 871154751090.dkr.ecr.eu-west-2.amazonaws.com/aggregator-service:latest
          ports:
            - name: http
              containerPort: 80