apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    metallb.universe.tf/allow-shared-ip: my-pool
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer